### ISSUE TITLE
[FEATURE] suggest new features

### ISSUE THREAD

**Issue by Frenziecodes** [Frenziecodes/Projest#21]

**Comment by krishnabansal89** [comment]
Comments and followers option can also be included.
Like viewer can comment it's views about the project and follow the particular developer for more interaction

**Comment by lewisushindi** [comment]
Nice! Can you work on that ?

**Comment by lewisushindi** [comment]
@krishnabansal89  nice idea. But it will need the users to create a profile account, so that the viewers can keep track of whom they followed, what project they liked. And get a notification once someone has replied to their comment . right ? Or is there any other way we can implement this feature ?

**Comment by Vee339** [comment]
I think we should improve the **UI of the home page**. It is looking like there are too many things on the screen and the attention of users would not be captured because they will be confused about where to focus.
In my opinion, we can:
1. Add some padding
2. make the page lengthy instead of wider.


![Uploading project-home-page.png…]()

**Comment by lewisushindi** [comment]
@Vee339 Regarding the padding, I agree that it could be useful to add some space between the elements on the page. This can help to create a more organized and visually appealing layout.
Expanding the length of the page is also an interesting idea. This could allow us to add more content to the page without making it too cluttered or overwhelming for users. Am opening a new issue about the improvement of the UI of the homepage so that we can work on it together.

**Comment by Palakkgoyal** [comment]
In the navbar when a link is active and when someone hover on the active link, the text of the link become dark which decrease the visibility of the text as the background of active link is also dark. So according to me there should be some changes for the enhancement of UX
![Screenshot (483)](https://user-images.githubusercontent.com/116902573/229718163-13044a8a-c519-4bef-afe7-e91d7befbe90.png)

**Comment by lewisushindi** [comment]
nice ! currently we are working on switching the project to react. We will be able to correct this issue . Thank you @Palakkgoyal

**Comment by lewisushindi** [comment]
Hey @Vee339, I wanted to let you know that we've updated the UI of the homepage. Feel free to check it out at [projest](https://projest-290c8.web.app/) and let us know what you think!

**Comment by lewisushindi** [comment]
Thanks for your feedback, @Palakkgoyal . We've made some changes to improve the visibility of the active link text on hover, and we hope this enhances the UX. Let us know if you have any other suggestions for improvement. Thanks for helping us make Projest better!

**Comment by Vee339** [comment]
> Hey @Vee339, I wanted to let you know that we've updated the UI of the homepage. Feel free to check it out at [projest](https://projest-290c8.web.app/) and let us know what you think!

It's looking really great @lewisushindi . The site's design is looking sleek now and your efforts are clearly visible. However, I think the docs and contributing page have a lot of clutter. There would be good if there will be more padding on the page. 
If you want I can work on that.

**Comment by abhinav2712** [comment]
For the website to look more unique and branded, maybe it should have its own logo, I have some ideas regarding that in my mind, let me know if i can work on this

**Comment by lewisushindi** [comment]
Thank you, @abhinav2712, for expressing interest in working on the logo. Please feel free to proceed with the task and create a new issue regarding it
